//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConestogaConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string ActivityName { get; set; }
        public string Description { get; set; }
        public string ActivityType { get; set; }
        public System.DateTime Added_On { get; set; }
        public System.DateTime Updated_On { get; set; }
    }
}
